AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI + Mangum serverless app (HTTP API)

Globals:
  Function:
    Runtime: python3.13
    Timeout: 15
    MemorySize: 512

Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fastapi-mangum
      Handler: main.handler
      CodeUri: .
      AutoPublishAlias: live
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      Environment:
        Variables:
          ENV: production
      VpcConfig:
        SubnetIds:
          - subnet-053c56d790725d05c
          - subnet-00de03a2cb72415c6
          - subnet-0f9338d0bcd52ba8d
        SecurityGroupIds:
          - sg-05b53f16196c80299
          - sg-015e515c29708be80
      Events:
        ProxyApi:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  HttpApiUrl:
    Description: "HTTP API endpoint"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
